Feature/jwt
ReamFOX/online-book-store pull request #14
Opened 2024-04-11 14:02 UTC by ReamFOX

2024-04-11 15:24 UTC, andrii-hoienko requested changes
Please resolve all conflicts first

2024-04-12 09:40 UTC, yevheniisynytsia approved these changes
Well done! Left some naming comments. Also it contains changes from your previous PR that are not related to this PR. Please try to avoid such situations

2024-04-12 09:40 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/security/impl/JwtAuthFilter.java
> +    private static final String HEADER = "Authorization";
```suggestion
    private static final String AUTHORIZATION_HEADER_NAME = "Authorization";
```

2024-04-12 09:40 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/security/impl/JwtAuthFilter.java
> +    private static final String TYPE = "Bearer ";
```suggestion
    private static final String PREFIX_BEARER = "Bearer ";
```

2024-04-12 10:28 UTC, merged