Feature/cart model
ReamFOX/online-book-store pull request #17
Opened 2024-04-18 14:25 UTC by ReamFOX

2024-04-22 11:01 UTC, yevheniisynytsia requested changes
Left some comments, can be discussed

2024-04-22 11:01 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/controller/ShoppingCartController.java
> +                .getAuthentication();
```suggestion
    public CartItemDto addBookToCart(@RequestBody @Valid CreateCartItemRequestDto requestDto, Authentication authentication) {
        User user = (User) authentication.getPrincipal();
```

2024-04-22 11:01 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/controller/ShoppingCartController.java
> +    private final CartItemService itemService;
I think you should use `CartItemService` inside `ShoppingCartService` so that you call `ShoppingCartService` methods. It is not too trivial why the function is `addBookToCart`, but you call `itemService.saveByEmail`

2024-04-22 11:01 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/controller/ShoppingCartController.java
> +                .getAuthentication();
authentication can be autowired from params

2024-04-22 11:01 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/dto/item/CreateCartItemRequestDto.java
> +    @Min(value = 1, message = "Quantity can't be 0 or less")
`@Positive` is also an option

2024-04-22 11:01 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/entity/CartItem.java
> +@Table(name = "cart_items")
let's add soft delete

2024-04-22 11:01 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/entity/CartItem.java
> +    @ManyToOne
is it ok to have EAGER here?

2024-04-22 11:01 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/entity/ShoppingCart.java
> +    @OneToMany(fetch = FetchType.LAZY, mappedBy = "shoppingCart", cascade = CascadeType.REMOVE)
are you sure with it? Do we store new CartItems per every shopping cart and they belong only to it?

2024-04-22 11:01 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/mapper/CartMapper.java
> +public interface CartMapper {
```suggestion
public interface ShoppingCartMapper {
```

2024-04-22 11:01 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/repository/ShoppingCartRepository.java
> +    Optional<ShoppingCart> findByUser_Email(String email);
let's use user id, it is easier to use

2024-04-22 11:01 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/service/impl/CartItemServiceImpl.java
> +    public CartItemDto saveByEmail(CreateCartItemRequestDto requestDto, String email) {
this all class feels for me like a `shopping cart service` functionality. Like `addToCart()` is looks for the book by id, looks for the user by id, looks by shopping cart by d and if OK it creates a cart item

2024-04-22 11:01 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/service/impl/CartItemServiceImpl.java
> +    public CartItemDto saveByEmail(CreateCartItemRequestDto requestDto, String email) {
this should be `@Transactional`

2024-04-22 11:01 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/service/impl/CartItemServiceImpl.java
> +    public CartItemDto updateByEmail(Long id, String email, UpdateCartItemDto updateDto) {
same for transactional

2024-04-22 15:01 UTC, ReamFOX commented on src/main/java/com/farion/onlinebookstore/entity/ShoppingCart.java
> +    @OneToMany(fetch = FetchType.LAZY, mappedBy = "shoppingCart", cascade = CascadeType.REMOVE)
It seemed logical to me, but maybe I was wrong, I'll ask about it

2024-04-23 13:30 UTC, andrii-hoienko approved these changes
Good job!

2024-04-23 13:30 UTC, andrii-hoienko commented on src/main/java/com/farion/onlinebookstore/dto/item/UpdateCartItemDto.java
> +    @NotNull
Int could not be null, so I believe Min annotation will be enough, or you can make int -> Integer

2024-04-23 13:38 UTC, merged