Feature/book tests
ReamFOX/online-book-store pull request #26
Opened 2024-05-07 15:11 UTC by ReamFOX

2024-05-10 13:50 UTC, andrii-hoienko requested changes
Good job! Left some comments

2024-05-10 13:50 UTC, andrii-hoienko commented on src/test/java/com/farion/onlinebookstore/controller/BookControllerTest.java
> +        EqualsBuilder.reflectionEquals(booksFromDB.get(testId), actual);
```suggestion
        int testId = 5;
        BookDto expected= ...
        

        MvcResult result = mockMvc.perform(MockMvcRequestBuilders.get(BOOK_ENDPOINT + SLASH + testId))
                .andExpect(status().is2xxSuccessful())
                .andReturn();
                
        BookDto actual =
                objectMapper.readValue(result.getResponse().getContentAsString(), BookDto.class);

        EqualsBuilder.reflectionEquals(booksFromDB.get(testId), actual);
```

2024-05-10 13:50 UTC, andrii-hoienko commented on src/test/java/com/farion/onlinebookstore/controller/BookControllerTest.java
> +                });
What is the reason to write TypeReference?

2024-05-10 13:50 UTC, andrii-hoienko commented on src/test/java/com/farion/onlinebookstore/controller/BookControllerTest.java
> +        }
I suggest to move this logic to util class and reuse when required, or use library that allows to assert collections

2024-05-10 13:50 UTC, andrii-hoienko commented on src/test/java/com/farion/onlinebookstore/controller/CategoryControllerTest.java
> +    }
I suggest to parse object received from  mockMvc.perform to business object and compare using asserEquals

2024-05-10 13:50 UTC, andrii-hoienko commented on src/test/java/com/farion/onlinebookstore/util/ConstUtil.java
> +public class ConstUtil {
```suggestion
public class Constants { //TestObjectMother as an alternative name, and you can move here methods that create test objects 
```

2024-05-10 13:50 UTC, andrii-hoienko commented on src/test/java/com/farion/onlinebookstore/util/ConstUtil.java
> +        throw new RuntimeException("This constructor shouldn`t invoke");
```suggestion

```

2024-05-10 14:53 UTC, ReamFOX commented on src/test/java/com/farion/onlinebookstore/controller/BookControllerTest.java
> +                });
I found this as an option to use a mapper for a collection, but I can also use another option.

2024-05-14 11:32 UTC, vovasalyha approved these changes

2024-05-14 11:35 UTC, merged