Dev
ReamFOX/online-book-store pull request #3
Opened 2024-03-29 19:02 UTC by ReamFOX

2024-04-01 15:27 UTC, SkillfulDev requested changes
The code looks good for this task. But if you take a look at the first task about creating repo , you will see that you didn`t add CI at all. So your code doesn`t check by CI.

2024-04-01 15:27 UTC, SkillfulDev commented on src/main/java/com/farion/onlinebookstore/OnlineBookStoreApplication.java
>  	private BookService bookService;
Why do you need it?

2024-04-01 15:57 UTC, ReamFOX commented on src/main/java/com/farion/onlinebookstore/OnlineBookStoreApplication.java
>  	private BookService bookService;
Oh, I forgot to delete it, thanks

2024-04-04 13:46 UTC, andrii-hoienko requested changes
Left minor comment

2024-04-04 13:46 UTC, andrii-hoienko commented on checkstyle.xml
> +<?xml version="1.0" encoding="UTF-8"?>
What is the reason to change it?

2024-04-04 14:25 UTC, closed without merging