Feature/data validation
ReamFOX/online-book-store pull request #6
Opened 2024-04-04 10:11 UTC by ReamFOX

2024-04-05 13:44 UTC, andrii-hoienko requested changes
Good job! Left minor comments

2024-04-05 13:44 UTC, andrii-hoienko commented on src/main/java/com/farion/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    }
Could you please add some methods to hadle specific exception that you throw

2024-04-05 13:44 UTC, andrii-hoienko commented on src/main/java/com/farion/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, headers, status);
Move string literals to constants

2024-04-05 13:44 UTC, andrii-hoienko commented on src/main/java/com/farion/onlinebookstore/dto/CreateBookRequestDto.java
> +    @ISBN(message = "invalid format")
```suggestion
    @ISBN(message = "invalid isbn format")
```

2024-04-05 13:44 UTC, andrii-hoienko commented on src/main/java/com/farion/onlinebookstore/dto/CreateBookRequestDto.java
> +    @Size(max = 255, message = "can`t be longer than 255 characters")
```suggestion
    @Size(max = 255, message = "Description can`t be longer than 255 characters")
```

2024-04-05 13:44 UTC, andrii-hoienko commented on src/main/java/com/farion/onlinebookstore/dto/CreateBookRequestDto.java
> +    @Size(max = 255, message = "can`t be longer than 255 characters")
Make same changes where possible

2024-04-08 10:06 UTC, yevheniisynytsia requested changes

2024-04-08 10:06 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/controller/BookController.java
>      public BookDto updateById(@PathVariable Long id, @RequestBody CreateBookRequestDto requestDto) {
```suggestion
    public BookDto updateById(@PathVariable Long id, @RequestBody @Valid CreateBookRequestDto requestDto) {
```

2024-04-08 10:06 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/dto/CreateBookRequestDto.java
> +    @NotEmpty
let's use `@NotBlank`
https://www.baeldung.com/java-bean-validation-not-null-empty-blank

2024-04-08 10:36 UTC, yevheniisynytsia requested changes

2024-04-08 10:36 UTC, yevheniisynytsia commented on src/main/java/com/farion/onlinebookstore/dto/CreateBookRequestDto.java
>      @ISBN(message = "invalid isbn format")
`@ISBN` accepts nulls, consider adding validation for it, you can use `@NotBlank` as well

2024-04-08 10:40 UTC, merged